### ISSUE TITLE
Use the gh-pages branch

### ISSUE THREAD

**Issue by bnjmnt4n** [bterlson/ecmascript#7]
Creating a branch called gh-pages allows you to access all the repo’s content via https://bterlson.github.io/ecmascript. You can also rename the current master branch to that and set it as the default branch.

**Comment by mathiasbynens** [comment]
+1

**Comment by fpereira1** [comment]
+1

**Comment by mathiasbynens** [comment]
@fpereira1 @d10 See https://github.com/tc39/ecma262 & https://tc39.github.io/ecma262/.
